export const DB_KEYS = {
  FOOTER_CONTENT: "footer_content",
  MENU_CONTENT: "menu_content",
  CONVENTIONS_HERO: "conventions_hero_image",
  FORMATIONS_HERO: "formations_hero_image",
  PUBLICATIONS_HERO: "publications_hero_images",
  ACTUALITES_HERO: "actualites_hero_image",
  LIENS_UTILES_HERO: "liens_utiles_hero_image",
  VOCABULAIRE_HERO: "vocabulaire_hero_image",
  PARTICULIERS_HERO: "particuliers_hero_image",
  ENTREPRISES_HERO: "entreprises_hero_image",
  LA_FMA_STATS_IMAGE: "la_fma_stats_image",
  SITE_LOGO: "site_logo",
  SITE_SPINNER: "site_spinner_logo",
  HOME_CONTENT: "home_content",
  LA_FMA_CONTENT: "la_fma_content",
  CONTACT_CONTENT: "contact_content",
  CONTACT_HERO: "contact_hero_image",
  CHIFFRES_CLES_CONTENT: "chiffres_cles_content",
  SITE_THEME: "site_theme_colors",
  ADMIN_THEME: "admin_theme_colors",
} as const;
